Install and configure proxytrack (WIP)
osuosl-cookbooks/proxytrack pull request #1
Opened 2020-02-13 20:16 UTC by Vancelot11

2020-02-14 18:14 UTC, ramereth commented
![](https://github.trello.services/images/mini-trello-icon.png) [LF Archived Website Migration](https://trello.com/c/CcakKTMo/33-lf-archived-website-migration)

2020-02-18 18:31 UTC, ramereth requested changes

2020-02-18 18:31 UTC, ramereth commented on .kitchen.yml
> +      - recipe[proxytrack-test::resource_test]
Since this is primarily a resource cookbook, let's just test this all in one suite.

2020-02-18 18:31 UTC, ramereth commented on resources/proxytrack.rb
> +  end
Please use the [systemd_unit resource](https://docs.chef.io/resource_systemd_unit.html) to manage this instead.

2020-02-25 00:40 UTC, ramereth requested changes

2020-02-25 00:40 UTC, ramereth commented on resources/proxytrack.rb
> +    content <<-EOU.gsub(/^\s+/, '')
I generally prefer to use ``EOF``.
```suggestion
    content <<-EOF.gsub(/^\s+/, '')
```

2020-02-25 00:40 UTC, ramereth commented on resources/proxytrack.rb
> +    User=centos
This user isn't always going to exist. I think a better option is to create a ``user`` parameter and default it to the ``nobody`` user.

2020-02-25 00:40 UTC, ramereth commented on resources/proxytrack.rb
> +end
IMO, the ``:create`` action should enable and start the service by default. In addition, I'd prefer we use the ``service`` resource for enabling/starting theses. The same would be for the ``:delete`` action with the inverse actions.

2020-02-25 00:40 UTC, ramereth commented on resources/proxytrack.rb
> +end
I don't think this is needed since we're not loading a configuration and a restart of the process would be required for any changes.

2020-02-25 00:40 UTC, ramereth commented on .kitchen.yml
>        - recipe[proxytrack::default]
I don't think this is needed since you include it in the resource.

2020-02-25 00:40 UTC, ramereth commented on test/cookbooks/proxytrack-test/recipes/resource_test.rb
> +end
One of these should test changing the ``proxy_address`` and ``icp_address`` to listen on ``0.0.0.0`` since we'll need that in production.

2020-02-25 00:40 UTC, ramereth commented on resources/proxytrack.rb
> +property :proxy_address,      String
Should this default to something like ``0.0.0.0`` or ``localhost``?

2020-02-26 21:57 UTC, ramereth requested changes
Getting closer!

2020-02-26 21:57 UTC, ramereth commented on resources/proxytrack.rb
> +    User=#{user}
```suggestion
    User=#{new_resource.user}
```

2020-02-26 21:57 UTC, ramereth commented on resources/proxytrack.rb
>  end
These can be removed AFAIK.

2020-02-26 21:57 UTC, ramereth commented on resources/proxytrack.rb
> +  action_disable
Instead of this, I think you should have the service resource here doing a disable, stop actions.

2020-02-28 21:01 UTC, ramereth approved these changes
Please do a major bump by doing the following (since this is a new cookbook): ``!bump major``. Then create a new PR which adds a version lock to the production env.

2020-03-09 20:21 UTC, Vancelot11 commented
!bump major

2020-03-09 20:21 UTC, merged

2020-03-09 20:22 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a major-level version bump to v1.0.0.  Have a nice day!