Refactor resource
osuosl-cookbooks/proxytrack pull request #2
Opened 2020-04-07 16:53 UTC by Vancelot11

2020-04-07 17:09 UTC, ramereth requested changes
Please also update ChefSpec

2020-04-07 17:09 UTC, ramereth commented on resources/proxytrack.rb
> +    notifies :restart, "service[proxytrack-#{new_resource.name}]", :immediately
I don't think we need to restart this immediately.
```suggestion
    notifies :restart, "service[proxytrack-#{new_resource.name}]"
```

2020-04-07 17:09 UTC, ramereth commented on resources/proxytrack.rb
> +    action [:stop, :disable]
You should probably move this above the ``systemd_unit`` resource since that deletes the unit.

2020-04-07 17:09 UTC, ramereth commented
![](https://github.trello.services/images/mini-trello-icon.png) [LF Archived Website Migration](https://trello.com/c/CcakKTMo/33-lf-archived-website-migration)

2020-04-07 17:50 UTC, ramereth commented on spec/proxytrack-test/resource_test_spec.rb
> +      it { expect(chef_run).to start_service('proxytrack-test.com') }
Can you add a test for the notification please?

2020-04-07 18:15 UTC, ramereth commented on spec/proxytrack-test/resource_test_spec.rb
> +      it { expect(unit).to notify('service[proxytrack-test.com]').to(:restart) }
I'd prefer we go with this and remove the ``let`` statement above.
```suggestion
      it { expect(chef_run.systemd_unit('proxytrack-test.com.service')).to notify('service[proxytrack-test.com]').to(:restart) }
```

2020-04-07 22:19 UTC, ramereth approved these changes
Please do a patch bump.

2020-04-09 16:16 UTC, Vancelot11 commented
!bump patch ~

2020-04-09 16:17 UTC, merged

2020-04-09 16:17 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v1.0.1.  Have a nice day!